### ISSUE TITLE
Tambah period ERROR

### ISSUE THREAD

**Issue by ifirmawan** [sabirudev/redmetric-frontend#44]
<img width="983" alt="Screen Shot 2021-08-25 at 19 33 26" src="https://user-images.githubusercontent.com/20871229/130791331-f35bc29d-ad50-4c06-883b-3e590573a5bc.png">

**Comment by ifirmawan** [comment]
payloadnya kosong @sabirudev

**Comment by sabirudev** [comment]
![image](https://user-images.githubusercontent.com/85658355/130791766-7d2a883c-0342-4539-ac7a-5035d045a5b2.png)

Belum ada Add @ifirmawan

**Comment by ifirmawan** [comment]
owala, sorry. belum aku buat di dokumentasinya. tapi di Backend udah ada gus

[Api/PeriodApiController.php#L51](https://github.com/sabirudev/redmetric-backend/blob/master/app/Http/Controllers/Api/PeriodApiController.php#L51)

**Comment by ifirmawan** [comment]
payloadnya sama kaya update @sabirudev cuma beda is_ended ga ada
```
{
    "opened": "2021-07-05",
    "closed": "2021-07-19"
}
```
