### ISSUE TITLE
Bug Card berita 

### ISSUE THREAD

**Issue by ifirmawan** [sabirudev/redmetric-frontend#46]
![Screen Shot 2021-08-26 at 06 30 12](https://user-images.githubusercontent.com/20871229/130877486-2f85248c-f55e-4ee2-b51a-699fc35b3f5e.png)
Pisahkan antara Judul link dengan deskripsi singkat

**Comment by ifirmawan** [comment]
# Biar gampang
Diubah jadi list seperti ini
![Screen Shot 2021-08-26 at 06 37 56](https://user-images.githubusercontent.com/20871229/130878194-55277d38-044f-4c39-a676-7de495ada016.png)


## SEE MORE
Diganti jadi gini, 🔝  diatasnya list 
![Screen Shot 2021-08-26 at 06 40 10](https://user-images.githubusercontent.com/20871229/130878213-6082b533-90af-4496-8f42-965dd0bceade.png)

**Comment by sabirudev** [comment]
Okee Noted Wan
